security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    - {name: admin, password: 123, roles: [ROLE_ADMIN]}
                    - {name: normal, password: 123, roles: [ROLE_USER]}
    firewalls:
        dev:  
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/, role: ROLE_USER }

    